In [1]:
import geopandas as gpd
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
from shapely import wkt

In [3]:
df = pd.read_csv('../data/ads24-railways.csv', low_memory=False)
df

             id     railway                                                wkt
0       4945353  dismantled  LINESTRING(21.015705800000003 52.221566,21.015...
1       4990565        rail  LINESTRING(21.0438805 52.247502700000005,21.04...
2       4990566        rail  LINESTRING(21.0420424 52.2412129,21.0420975 52...
3       4990567        rail  LINESTRING(21.029751700000002 52.2344881,21.02...
4       5000677        rail  LINESTRING(21.0556264 52.2632842,21.0545974000...
...         ...         ...                                                ...
130384  4820685        rail  LINESTRING(19.8524295 50.0863188,19.8523603 50...
130385  4820931        rail  LINESTRING(18.1960821 54.277320100000004,18.19...
130386  4820939        rail  LINESTRING(17.7118431 54.108859,17.7122934 54....
130387  4820953     disused  LINESTRING(17.7559542 54.535678700000005,17.75...
130388  4820973        rail  LINESTRING(18.025377000000002 54.2066599000000...

[130389 rows x 3 columns]

In [5]:
df['geometry'] = df['wkt'].apply(wkt.loads)
gdf = gpd.GeoDataFrame(df, crs="EPSG:4326", geometry='geometry')
gdf['lat'] = gdf.centroid.y
gdf['long'] = gdf.centroid.x

gdf.to_crs(epsg=2180, inplace=True)
gdf['wkt'] = gdf['geometry'].apply(wkt.dumps)
gdf = gdf.drop(['geometry'], axis=1)
gdf

/tmp/ipykernel_131172/2526851929.py:3: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf['lat'] = gdf.centroid.y
/tmp/ipykernel_131172/2526851929.py:4: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf['long'] = gdf.centroid.x

,id,railway,wkt,lat,long
0,4945353,dismantled,LINESTRING (637646.6943869570968673 485859.551...,52.221499,21.015626
1,4990565,rail,LINESTRING (639489.1106968688545749 488796.986...,52.247722,21.043944
2,4990566,rail,LINESTRING (639383.3916411834070459 488094.171...,52.242029,21.042864
3,4990567,rail,LINESTRING (638565.5023479019291699 487322.956...,52.233893,21.028135
4,5000677,rail,LINESTRING (640240.8523103945190087 490574.199...,52.263419,21.055112
...,...,...,...,...,...
130384,4820685,rail,LINESTRING (560962.9822666230611503 246910.806...,50.097036,19.835845
130385,4820931,rail,LINESTRING (447670.6689454739098437 712870.162...,54.276958,18.195816
130386,4820939,rail,LINESTRING (415809.8421796221518889 694600.835...,54.101845,17.747242
130387,4820953,disused,LINESTRING (419530.1011325617437251 742022.117...,54.536645,17.758805
130388,4820973,rail,LINESTRING (436450.7944612383726053 705150.896...,54.198901,18.010649